### ISSUE TITLE
0 out of 85045 passed blat criteria

### ISSUE THREAD

**Issue by gianfilippo** [djhn75/RNAEditor#10]
Hi,

I am running with GATK 3.7. The pipeline was failing at the UnifiedGenotyper step in CallEditingSites.py. The issue is that the stand_emit_conf flag is no longer supported. I could not find a replacement flag in the GATK documentation for the UnifiedGenotyper, so I decided to remove the flag. It solves the problem, but I am not sure it is the way to go.
Eventually the pipeline fails again, see below from the log file:

created fasta file /home/gc223/scratch60/rnaEditor/Sample1.R1/Sample1.R1.noBlat.vcf_tmp.fa ***
	*** [DONE] Duration [0:05:21.294215] ***
*** INFO:    [Mon Apr 17 17:39:49 2017] * * * do blat search for unique reads * * * ***
	*** [DONE] Duration [0:05:15.518185] ***
*** INFO:     [Mon Apr 17 17:34:28 2017] Blat finished ***
*** INFO:     [Mon Apr 17 17:34:28 2017] Parse Blat output to look for non uniquely mapped reads ***
*** INFO:     [Mon Apr 17 17:34:28 2017] Analyse Blat hits (Slow) ***
*** INFO:     [Mon Apr 17 17:34:28 2017] Deleting invalid variants ***
*** INFO:    		 0 out of 85045 passed blat criteria ***
*** INFO:    		 85045 Missmatches had fewer than 2 missmatching-Reads. ***
*** INFO:    		 0 Missmatches had more missaligned reads than correct ones. ***
	*** [DONE] Duration [0:10:41.003859] ***
*** INFO:    [Mon Apr 17 17:45:09 2017] Print Variants to /home/gc223/scratch60/rnaEditor/Sample1.R1/Sample1.R1.noBlat.vcf ***
*** INFO:    Delete non Editing Bases (keep only T->C and A->G) ***
*** INFO:     [Mon Apr 17 17:45:09 2017] Annotating Variants ***
	*** [DONE] Duration [0:00:01.175382] ***
*** INFO:    [Mon Apr 17 17:45:10 2017] Print Variants to /home/gc223/scratch60/rnaEditor/Sample1.R1/Sample1.R1.editingIslands.bed ***
*** INFO:    [Mon Apr 17 17:45:10 2017] Print Genes and Variants to /home/gc223/scratch60/rnaEditor/Sample1.R1/Sample1.R1.editingSites.nonAlu.gvf ***
*** ERROR:    RnaEditor Failed ***

It turns out that the 
editingSites.nonAlu.gvf and editingSites.nonAlu.summary are empty because, as reported in the log file:
0 out of 85045 passed blat criteria

Can you please help/comment on this issue ?

Thanks
Gianfilippo

**Comment by gianfilippo** [comment]
Hi,

can you please help me with this issue ? I am stuck on this

Thanks

**Comment by djhn75** [comment]
Hi, the stand_emit_conf flag is necesarry, you should probaply install an earlier version of GATK, because this flag forces GATK to emit every single missmatch. 

Please send me the whole log file so i can see if there any additional informations.

Best regards
