### ISSUE TITLE
Dependencies question, and website is down

### ISSUE THREAD

**Issue by kthlnktng** [djhn75/RNAEditor#13]
Hello!

I'm interested in using RNAEditor and am running into a few problems:

1. I would like to run the program on a Linux cluster. Unfortunately, I am unable to install dependencies to ` /usr/local/bin/`. What is the recommended solution to get around this issue? Install the dependencies to one directory and modify the `sourceDir` line in `configuration.txt`? 
2. I'd like to access the human and mouse input files at http://rnaeditor.uni-frankfurt.de, but the website is down. Is there an alternative place where these are available?

Thanks,
Kathleen

**Comment by djhn75** [comment]
Dear Kathleen, thanks for your interest in RNAEditor. To answer your questions:

1. Yes you can simply install all the programs to one directory and add this directory to the configuration.txt sourceDir variable

2. We currently having problems with our server and are trying to fix them soon, untill then you can download the software from github or from the following link: https://drive.google.com/file/d/0B4WdFW9Uw3mcVXZQNHVGWnpnbW8/view?usp=sharing

The annotation is available here: 

- GRCH38: http://141.2.194.197/rnaeditor_annotations/GRCH38.tar.gz

- CRCH37: http://141.2.194.197/rnaeditor_annotations/GRCH37.tar.gz

- GRCM38: http://141.2.194.197/rnaeditor_annotations/GRCM38.tar.gz

Sorry again for the downtime of the server.

**Comment by kthlnktng** [comment]
Thanks for the quick response, and for providing the annotation files! 

I'll try out the suggested installation method, and will let you know if I run into any issues. 

As a sidenote, I've been having difficulties accessing the supplementary data from the paper through my institution. Is it possible to send along a copy?

**Comment by djhn75** [comment]
Dear Kathleen,  The Website should be online again under: [http://rnaeditor.uni-frankfurt.de/](http://rnaeditor.uni-frankfurt.de/)

The supplementary table is available [here](https://www.dropbox.com/s/y9ljkburbqz8fio/Table1.pdf?dl=0): 

Greetings David
