### ISSUE TITLE
0 out of 66386 passed blat criteria 

### ISSUE THREAD

**Issue by thestarocean** [djhn75/RNAEditor#14]
I was running RNAeditor on my RNA-seq data. Although there is indeed content in both editingSites.alu.gvf and editingSites.nonalu.gvf, I notice the log with information:

*** STATUS: [Thu 03 Aug 2017 08:43:02 AM ] Search non uniquely mapped reads ***
*** STATUS: [Thu 03 Aug 2017 08:43:02 AM ] Blat finished ***
*** STATUS: [Thu 03 Aug 2017 08:43:02 AM ] Parse Blat output to look for non uniquely mapped reads ***
*** STATUS: [Thu 03 Aug 2017 08:43:02 AM ] Analyse Blat hits (Slow) ***
*** STATUS: [Thu 03 Aug 2017 08:43:02 AM ] Deleting invalid variants ***
*** STATUS: 0 out of 66386 passed blat criteria ***
*** STATUS: 66386 Missmatches had fewer than 2 missmatching-Reads. ***
*** STATUS: 0 Missmatches had more missaligned reads than correct ones. ***

Is this a common problem? I use GATK version 3.5 with java 1.7 following your instruction.

**Comment by djhn75** [comment]
Yes i already recognised this message, but if the  editingSites.nonalu.vcf file is not empty you can ignore this message. It seems that under specific conditions the counter for passed reads is not incremented. Where working on a solution for this problem.
Thanks for your feedback, greetings David
