### ISSUE TITLE
Name conflict in CallEditingSites.py

### ISSUE THREAD

**Issue by thestarocean** [djhn75/RNAEditor#15]
Your RNAeditor provides a simple and quick method for identifying the RNA editing sites in RNA-seq data. However, when I reviewed the result, it occurred to me that non-alu vcf file is missing. So I read the code in CallEditingSites.py and found out that in line 469, line 472 and line 479, the output file for non-alu variants, non-alu variant clusters and alu variant clusters are the same. (".editingIsland.bed"). I think the first output file should be ".editingSites.nonalu.vcf" and the second should be ".editingIsland.nonalu.bed" and the final one should be ".editingIsland.alu.bed".
Is this the reason for the missing non-alu vcf file? Or the RNAeditor only give vcf file for alu editing sites?

**Comment by djhn75** [comment]
Thanks for your bug report. It is really highly appreciated.
I fixed the bug now on the github repository.
