### ISSUE TITLE
RNAEditor drop files

### ISSUE THREAD

**Issue by makijata** [djhn75/RNAEditor#17]
Hi, 
I tried to drop in the input tab both FASTQ and BAM files after launching RNAEditor.py. However without success...
Any suggestions what to try?

Thank you!

**Comment by djhn75** [comment]
Could you please send me the exact error message from the log file?

We highly recommend to follow the original pipeline to avoid false
positive variations. 

My guess is that during the realignment step GATK adds additional
attributes to the bam file, which are needed for variant calling. Therefore if your bam file is not mapped with RNAEditor, the Variant Calling step fails.

**Comment by makijata** [comment]
Thank you for your response. Below are the screenshots of what happens if I try to drag a fastq file. The only thing appearing on Ubuntu ones I ran python RNAEditor.py is:
Unknown property background size
Unknown property background size

and then it opens the window of RNAEditor.

![dsc_2952](https://user-images.githubusercontent.com/38926144/39598638-93a4ec06-4f19-11e8-9a74-2c1a2fba8524.JPG)
![dsc_2954](https://user-images.githubusercontent.com/38926144/39598639-93c15062-4f19-11e8-901c-c0dcfcf1e6c2.JPG)
![dsc_2955](https://user-images.githubusercontent.com/38926144/39598642-93df65e8-4f19-11e8-8d9c-f0836772aa53.JPG)
Any idea what might be the reason?

Thank you!

**Comment by djhn75** [comment]
You need to **extract the fastq file first**. At the moment you are trying to import a zipped file.

**Comment by makijata** [comment]
Thank you for your response. I tried also with the extracted files but still with no success...Any other suggestions? Maybe there is something wrong with the input tab... Would it help to re-install all the components?

**Comment by djhn75** [comment]
Hmm that sound unlikely to me. Can you start the analysis or can’t you even drop the fastq into the input tab ?  Are you working on Ubuntu?

You could also use the command line mode if the UI is morning properly on your computer

**Comment by makijata** [comment]
Thank you for your response. I can't even drop the fastq files and I am using Ubuntu. Is there a way to give the command to start the processing of fastq files without launching rnaeditor.py?

**Comment by djhn75** [comment]
Yes you can simply run `python RNAEditor.py -h `
For more information just look here: http://rnaeditor.uni-frankfurt.de/gettingStarted.php
