### ISSUE TITLE
GTF file button does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by tweirick** [djhn75/RNAEditor#3]
I haven't tested it on other operating systems, so this could happen elsewhere. The button to specify the path to a GTF file doesn't open a window like the other buttons.

**Comment by djhn75** [comment]
Thanks, the problem is fixed now...
Thanks Tyler 
[Commit](https://github.com/djhn75/RNAEditor/commit/fa3b56e1664c862271a5a3b2a50796243b2895c8)
