### ISSUE TITLE
PyQt4 is out of date, Please update to PyQt5/6

### ISSUE THREAD

**Issue by jowodo** [djhn75/RNAEditor#32]
I'm trying to install the dependencies and RNAEditor in a HPC environment but PyQt4 was last updated 2015[1]. 
It mentions being compatible with python2 and python3 but I can't download it with pip from python 2.7.18, 3.9.0, 3.10.4. 
Neither could I find it in an official conda repo[2] or when searching on pypi[3]. 

Please update the dependencies in the scripts to pyqt5 or higher. 

[1] https://pypi.org/project/PyQt4/
[2] https://anaconda.org/search?q=pyqt4+
[3] https://pypi.org/search/?q=pyqt4&o=

**Comment by djhn75** [comment]
Please see this updated version. still some testing should be done.
But it should work to make the first analysis. 

Please let me know if it worked on your side

https://github.com/djhn75/RNAEditor/releases/tag/RNAEditor_v1.1_alpha

**Comment by jowodo** [comment]
Thanks I'll will test it within the next few days and get back to you.

**Comment by jowodo** [comment]
I finally managed to find some time to install and test. I noticed some things: 
- `python` is not found as python2 is being phased out
I used `sed -i "s@#!/usr/bin/python@#!/usr/bin/env python3@" RNAEditor.py` to circumvent. 
I managed to execute: 
`RNAEditor.py -h`, but executing `RNAEditor.py` gives me: 
`ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'`
So I found that this might be resolved with a lower PyQt5 version [on StackOverflow](https://stackoverflow.com/questions/53137834/modulenotfounderror-no-module-named-pyqt5-qtwebenginewidgets#53852037)
So I installed `PyQt5==5.7.1` into my python3.10 virtual environment 
Now, I get 
`ModuleNotFoundError: No module named 'sip'`
even though I explicitly installed it via pip into the venv. 
I'll keep you updated.

**Comment by jowodo** [comment]
I managed to get further (I think) by replacing 
`pip install PyQt5=5.7.1 sip` with `pip install PyQtWebEngine`.[1] 
I'm running into another problem, though. 
```
*** INFO:    CHECK DEPENDENCIES ***
NoneType: None

Traceback (most recent call last):
  File "/scratch/students/apptest/2022-09-02-rnaeditor/1.1_alpha/rnaeditor.git/RNAEditor.py", line 323, in <module>
    edit=RnaEdit(args.input,parameters,0)
  File "/scratch/students/apptest/2022-09-02-rnaeditor/1.1_alpha/rnaeditor.git/RNAEditor.py", line 73, in __init__
    self.checkDependencies()
  File "/scratch/students/apptest/2022-09-02-rnaeditor/1.1_alpha/rnaeditor.git/RNAEditor.py", line 184, in checkDependencies
    Helper.error("BWA not found in %s" % self.params.sourceDir,self.logFile,self.textField)
  File "/scratch/students/apptest/2022-09-02-rnaeditor/1.1_alpha/rnaeditor.git/Helper.py", line 755, in error
    raise Exception("\n\n" + Helper.prefix + "ERROR:    " + message + Helper.praefix + "\n\n")
Exception:

*** ERROR:    BWA not found in /usr/local/bin/ ***
```
The problem is that I can't install anything at `/usr/local/bin` because I'm on a multiuser HPC system. 
We use [modules](http://modules.sourceforge.net/) to install different software and versions. 
That means the `bwa` and other executables  can be found through the `$PATH` variable and not in `/usr/local/bin/`
It would be great to make it possible to use the software, if the dependencies are not located in `/usr/local/bin`. 
Should I open a new issue and close this one? 

Best,
Pur

[1] https://stackoverflow.com/questions/51154871/python-3-7-0-no-module-named-pyqt5-qtwebenginewidgets

**Comment by djhn75** [comment]
![ForGithub](https://user-images.githubusercontent.com/5654514/189682554-c9ca439b-b1a7-4ea7-99da-86f11e3ad8bc.jpg)


There is a text box in the user interface which is called "Source directory" (see attachement) of for the Terminal mode you can set the variabale "sourceDir = /usr/local/bin/" in the configuration.txt file. This you can also simply drag and drop to the user interface by the way.

So you can set the directory where you programs need to be installed.

Let me know if you need additional help.

**Comment by jowodo** [comment]
Thanks for the hint! 
I've created a folder and will soft link all dependencies there. 
linking `bwa` worked after adding a trailing slash to the sourceDir path. 
My picard and GATK installation are missing following executables: 
- `$sourceDir/picard-tools/SortSam.jar`
- `$souceDir/picard-tools/GenomeAnalysisTK.jar
- `${sourceDir}/GATK/MarkDuplicates.jar
and even the directories don't exist. We didn't have any problems with these installation up to now. 
I'll try to install them from the links you provide in the README and get back to you.

**Comment by jowodo** [comment]
Hi, 

the person who wanted to have the software installed doesn't reply. 
I will stop working on this issue because my time is limited and a lot is already overdue. 

Thanks a lot for your support!
