### ISSUE TITLE
Error @ Parsing Variant Data

### ISSUE THREAD

**Issue by ghost** [djhn75/RNAEditor#4]
Hello,

I've been trying to use RNAEditor to assess editing in my RNAseq fastq. 
During the 'Parsing Variant Data' step I cam across the error message 'RnaEditor failed' with no additional information to troubleshoot. 

What should I do to rectify the error?

Thanks.

**Comment by djhn75** [comment]
RNAEditor creates a log file in the output folder with additional informations. Please check this file for more detailed infos.
