### ISSUE TITLE
Problem:  Identify Target Regions for realignment failed!!!

### ISSUE THREAD

**Issue by WYSNI** [djhn75/RNAEditor#9]
Hi,
I have a problem with your tool.
I have try a lot of fastq but i have always this issue:

*** INFO:     ***
*** INFO:    [Mon Apr 10 11:26:24 2017] * * * Align first Reads with BWA * * * ***
	*** [DONE] Duration [0:30:24.912421] ***
*** INFO:    [Mon Apr 10 11:56:49 2017] * * * Align second Reads with BWA * * * ***
	*** [DONE] Duration [0:29:36.256997] ***
*** INFO:    [Mon Apr 10 12:26:25 2017] * * * convert sai to sam * * * ***
	*** [DONE] Duration [0:19:35.044450] ***
*** INFO:    [Mon Apr 10 12:46:00 2017] * * * Sort Bam File * * * ***
	*** [DONE] Duration [0:12:52.086334] ***
*** INFO:    [Mon Apr 10 12:58:52 2017] * * * Index Bam File * * * ***
	*** [DONE] Duration [0:00:40.182976] ***
*** INFO:    [Mon Apr 10 12:59:33 2017] * * * Remove PCR duplicates * * * ***
	*** [DONE] Duration [0:12:31.083917] ***
*** INFO:    [Mon Apr 10 13:12:04 2017] * * * Identify Target Regions for realignment * * * ***
None

Traceback (most recent call last):
  File "RNAEditor.py", line 73, in run
    self.startAnalysis()
  File "RNAEditor.py", line 95, in startAnalysis
    mapResultFile=self.mapFastQ.startAnalysis()
  File "/sandbox/user/Linc_bam/RNAEditor/RNAEditor/MapFastq.py", line 178, in startAnalysis
    Helper.proceedCommand("Identify Target Regions for realignment", cmd, bamFile, intervalFile, self.rnaEdit)
  File "/sandbox/user/Linc_bam/RNAEditor/RNAEditor/Helper.py", line 271, in proceedCommand
    Helper.error(description+ " failed!!!",logFile,textField)
  File "/sandbox/user/Linc_bam/RNAEditor/RNAEditor/Helper.py", line 734, in error
    raise Exception("\n\n" + Helper.prefix + "ERROR:    " + message + Helper.praefix + "\n\n")
Exception: 

*** ERROR:    Identify Target Regions for realignment failed!!! ***

Traceback (most recent call last):
  File "RNAEditor.py", line 75, in run
    Helper.error("RnaEditor Failed",self.logFile,self.textField)
  File "/sandbox/user/Linc_bam/RNAEditor/RNAEditor/Helper.py", line 734, in error
    raise Exception("\n\n" + Helper.prefix + "ERROR:    " + message + Helper.praefix + "\n\n")
Exception: 

*** ERROR:    RnaEditor Failed ***

----------------------------------------------------------------------------------------------
I use GATK 3.5 as it explain. A contig problem maybe? I run it on a linux cluster. Is it a problem?

Best,

Wysni

**Comment by WYSNI** [comment]
It was a contig problem I close this issue

**Comment by aaiezza** [comment]
@WYSNI, would you perhaps be able to explain the config issue that you had encountered?
